version: "3.7"

networks:
  es-net:
    driver: bridge

volumes:
  es-data:
    driver: local

services:
  elasticsearch:
    container_name: draug-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-net
  kibana:
    container_name: draug-kibana
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - "ELASTICSEARCH_HOSTS=http://draug-elastic:9200"
    ports:
      - "5601:5601"
    networks:
      - es-net
